name: Deploy to droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to droplet
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 206.189.113.64
          username: root
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            cd nam-todo
            git pull origin main
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm install
            pm2 reload all